version: '3.9'

services:
  golang_server:
    image: VaradBelwalkar/golang_server
    ports:
      - "8080:8000"
    volumes:
      - ./config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PASSWORD_HASH_SECRET=${PASSWORD_HASH_SECRET}
      - OFFICIAL_EMAIL=${OFFICIAL_EMAIL}
      - OFFICIAL_EMAIL_APP_PASSWORD=${OFFICIAL_EMAIL_APP_PASSWORD}
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis

  mongodb:
    image: mongo
    restart: always
    volumes:
    - mndbdatabase:/data/db
    MONGO_INITDB_ROOT_USERNAME: <set_username_here>
    MONGO_INITDB_ROOT_PASSWORD: <set_password_here>

