apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-server
spec:
  replicas: 4
  selector:
    matchLabels:
      pod-label: golang-server-pod
  template:
    metadata:
      name: golang-server-pod-name
      labels:
        pod-label: golang-server-pod
    spec:
      containers:
      - name: golang-server-pod-container-name
        image: varadbelwalkar/golang_server
        volumeMounts:
           - name: configure
             mountPath: /app/config.json
             subPath: config.json
           - name: docker-socket
             mountPath: /var/run/docker.sock
             subPath: docker.sock
           - name: configure
             mountPath: /app/.env
             subPath: .env
      volumes:
        - name: configure
          hostPath:
            path: ./
        - name: docker-socket
          hostPath:
            path: /var/run/
---

apiversion: v1
kind: Service
metadata:
  name: golang-server-service
spec:
  type: LoadBalancer
  selector:
    pod-label: golang-server-pod

  ports:
  -  protocol: tcp
     port: 8000
     targetPort: 8000
     nodePort: 8000


