apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: mndbdatabase-claim
  labels:
    psvolume: mndbdatabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi

status: {}
