apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
  labels:
    db-name: mongodb-database

spec:
  selector:
    matchLabels:
      mongodb-pod: mongodb-pod-name

  template:
    metadata:
      name: mongodb-pod
      labels:
        mongodb-pod: mongodb-pod-name
    spec:
      containers:
      - name: mongodb-pod-container-name
        image: mongo
        volumeMounts:
          - name: dbstorage
            mountPath: /data/db
      volumes:
        - name: dbstorage
          persistentVolumeClaim:
            claimName: golang-server-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    mongodb-service-label: mongodb-service-label-name
spec:
  selector:
    mongodb-pod: mongodb-pod-name
  type: ClusterIP
  ports:
  -  protocol: TCP
     port: 27017
     targetPort: 27017

