apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: ps-volume
